# Generated by Django 5.0.2 on 2024-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_facturation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='apply_tax',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
